version: "3.8"
services:
  django:
    image: gr1902/mp_sales_updater
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    command: gunicorn --bind unix:/home/gr1902/mp_sales_updater/gunicorn.sock --workers 1 project.wsgi:application
    expose:
      - 8000
    volumes:
      - ./core/utils/webshare_proxies.txt:/home/gr1902/mp_sales_updater/core/utils/webshare_proxies.txt
      - static_volume:/home/gr1902/mp_sales_updater/static
      - media_volume:/home/gr1902/mp_sales_updater/media
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/:delegated
    env_file:
      - .docker/db.env
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/gr1902/mp_sales_updater/static
      - media_volume:/home/gr1902/mp_sales_updater/media
      - ./magic-stat.ru.crt:/etc/ssl/magic-stat.ru.crt
      - ./magic-stat.ru.key:/etc/ssl/magic-stat.ru.key
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: