version: "3.8"
services:
  web:
    image: gr1902/web
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    command: .docker/gunicorn_start.sh
    expose:
      - 8000
    volumes:
      - ./core/utils/webshare_proxies.txt:/home/gr1902/mp_sales_updater/core/utils/webshare_proxies.txt
      - ./logs:/home/gr1902/mp_sales_updater/logs
      - static_volume:/home/gr1902/mp_sales_updater/static
      - media_volume:/home/gr1902/mp_sales_updater/media
    restart: always
    depends_on:
      - db
  item_update:
    image: gr1902/web
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    command: ./manage.py update_data wildberries items --cpu_multiplayer 0.8
    volumes:
      - ./core/utils/webshare_proxies.txt:/home/gr1902/mp_sales_updater/core/utils/webshare_proxies.txt
      - ./logs:/home/gr1902/mp_sales_updater/logs
      - static_volume:/home/gr1902/mp_sales_updater/static
      - media_volume:/home/gr1902/mp_sales_updater/media
    restart: "no"
    depends_on:
      - db
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/:delegated
    env_file:
      - .docker/db.env
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/gr1902/mp_sales_updater/static
      - media_volume:/home/gr1902/mp_sales_updater/media
      - ./magic-stat.ru.crt:/etc/ssl/magic-stat.ru.crt
      - ./magic-stat.ru.key:/etc/ssl/magic-stat.ru.key
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
