version: '3'
services:
  postgresql:
    image: postgres:12
    env_file:
      - db.env
  mp_sales_updater:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - /core/utils/webshare_proxies.txt:/core/utils/webshare_proxies.txt
