version: '3.8'
services:
  mp_sales_updater:
    image: gr1902/mp_sales_updater
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: /home/gr1902/mp_sales_updater/entrypoint.prod.sh
    volumes:
      - ./core/utils/webshare_proxies.txt:/home/gr1902/mp_sales_updater/core/utils/webshare_proxies.txt
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
