version: "3.8"
services:
  django:
    image: gr1902/mp_sales_updater
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/gr1902/mp_sales_updater
    ports:
      - 8000:8000
    restart: always
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .docker/db.env
    restart: always

volumes:
  postgres_data:
