# Generated by Django 3.0.7 on 2020-06-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200626_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
