# Generated by Django 3.0.7 on 2020-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemcategory_mp_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='mp_link',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='orig_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_parsed_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='item/'),
        ),
    ]
