# Generated by Django 3.0.7 on 2020-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200630_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_parsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
