# Generated by Django 3.0.7 on 2020-07-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200701_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='item/')),
                ('mp_link', models.CharField(blank=True, max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mp_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marketplace')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(related_name='items', to='core.Image'),
        ),
    ]
