# Generated by Django 3.0.7 on 2020-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200702_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mp_link',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
