# Generated by Django 3.0.7 on 2020-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200709_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrevision',
            name='is_adult',
        ),
        migrations.RemoveField(
            model_name='itemrevision',
            name='is_digital',
        ),
        migrations.AddField(
            model_name='item',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
