# Generated by Django 3.0.7 on 2020-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200710_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
