# Generated by Django 3.0.7 on 2020-07-16 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_start_parse_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='next_parse_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parse_frequency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_parse_time',
        ),
        migrations.AddField(
            model_name='image',
            name='next_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='parse_frequency',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='image',
            name='start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='items_next_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='items_parse_frequency',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='item',
            name='items_start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='revisions_next_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='revisions_parse_frequency',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='item',
            name='revisions_start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='next_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='parse_frequency',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
