# Generated by Django 3.0.7 on 2020-07-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200717_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='colour',
            new_name='colours',
        ),
    ]
