# Generated by Django 3.0.7 on 2020-08-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200717_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no_individual_category',
            field=models.BooleanField(default=False),
        ),
    ]
