# Generated by Django 3.0.7 on 2020-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_item_no_individual_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_categories_filled',
            field=models.BooleanField(default=False),
        ),
    ]
