# Generated by Django 3.1 on 2020-08-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_item_is_categories_filled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='mp_id',
            new_name='marketplace_id',
        ),
        migrations.RenameField(
            model_name='colour',
            old_name='mp_id',
            new_name='marketplace_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='mp_link',
            new_name='marketplace_link',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mp_id',
            new_name='marketplace_id',
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='mp_category_url',
            new_name='marketplace_category_url',
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='mp_id',
            new_name='marketplace_id',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='mp_id',
            new_name='marketplace_id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='mp_source',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='mp_source',
        ),
        migrations.RemoveField(
            model_name='image',
            name='mp_source',
        ),
        migrations.RemoveField(
            model_name='item',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mp_source',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='mp_source',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='mp_source',
        ),
        migrations.AddField(
            model_name='brand',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colour',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='marketplace_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.marketplace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.seller'),
        ),
        migrations.AlterField(
            model_name='itemrevision',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_revisions', to='core.item'),
        ),
    ]
