# Generated by Django 3.1 on 2020-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200817_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marketplace_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
