# Generated by Django 3.1 on 2020-08-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_itemcategory_is_leaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_categories_filled',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_leaf',
        ),
    ]
