# Generated by Django 3.1 on 2020-08-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200825_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='parse_frequency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='items_parse_frequency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='no_individual_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='revisions_parse_frequency',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='parse_frequency',
        ),
        migrations.CreateModel(
            name='ItemPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('position_num', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_positions', to='core.itemcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_positions', to='core.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
