# Generated by Django 3.1 on 2020-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200831_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='marketplace_items_in_category',
            field=models.IntegerField(default=0),
        ),
    ]
