# Generated by Django 3.1 on 2020-09-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_itemcategory_marketplace_items_in_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_digital',
        ),
    ]
