# Generated by Django 3.1 on 2020-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_item_is_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items_next_parse_time',
            new_name='next_parse_time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='items_start_parse_time',
            new_name='start_parse_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='revisions_next_parse_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='revisions_start_parse_time',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='next_parse_time',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='start_parse_time',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_next_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_start_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_next_parse_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_start_parse_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
